=== SrirangaDigital/prabuddha-keralam/pke.dtd
<!ELEMENT pke (volume*)>
<!ELEMENT volume (part*)>
<!ATTLIST volume vnum CDATA #REQUIRED>
<!ELEMENT part (entry+)>
<!ATTLIST part pnum CDATA #REQUIRED>
<!ATTLIST part month CDATA #REQUIRED>
<!ATTLIST part year CDATA #REQUIRED>
<!ATTLIST part info CDATA #REQUIRED>
<!ELEMENT entry (title,feature,allauthors,page)>
<!ELEMENT title (#PCDATA|sup)*>
<!ELEMENT feature (#PCDATA)>
<!ELEMENT allauthors (author*)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT page (#PCDATA)>
<!ELEMENT sup (#PCDATA)*>

=== SrirangaDigital/prabuddha-keralam/2014-2015.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pke SYSTEM "pke.dtd">

<pke>
	<volume vnum="099">
		<part pnum="01" month="01" year="2014" info="">
			<entry>
				<title>അമൃതവാണി</title>
				<feature />
				<allauthors />
				<page>0001-0001</page>
			</entry>
			<entry>
				<title>ശ്രീരാമകൃഷ്ണവചനാമൃതം</title>
				<feature />
				<allauthors />
				<page>0002-0002</page>
			</entry>
			<entry>
				<title>സത്യദർശനം  (എഡിറ്റോറിയൽ)</title>
				<feature />
				<allauthors>
					<author>സദ്ഭവാനന്ദസ്വാമി</author>
				</allauthors>
				<page>0003-0004</page>
			</entry>
			<entry>
				<title>വിവേകചൂഡാമണി</title>
				<feature />
				<allauthors>
					<author>ശ്രീ രംഗനാഥാനന്ദസ്വാമികൾ</author>
				</allauthors>
				<page>0006-0013</page>
			</entry>
			<entry>
				<title>സ്വാമി തപസ്യാനന്ദ ( ജീവചരിത്രക്കുറിപ്പ് )</title>
				<feature />
				<allauthors>
					<author>സ്വാമി ത്യാഗാനന്ദ</author>
				</allauthors>
				<page>0014-0019</page>
			</entry>
			<entry>
				<title>ഹേ സാധകാ, സ്വാധ്യായത്തിൽ നീ വിട്ടുവീഴ്ച വരുത്തരുതേ</title>
				<feature />
				<allauthors>
					<author>ആചാര്യ എം. ആർ. രാജേഷ്</author>
				</allauthors>
				<page>0020-0021</page>
			</entry>
			<entry>
				<title>ശ്രീരാമകൃഷ്ണപാദങ്ങളിൽ (കവിത)</title>
				<feature />
				<allauthors>
					<author>പ്രൊഫ. തൃക്കൊടിത്താനം ഗോപിനാഥൻ നായർ</author>
				</allauthors>
				<page>0022-0022</page>
			</entry>
			<entry>
				<title>സ്വാമിജി പാശ്ചാത്യർക്ക് നൽകിയ സന്ദേശം</title>
				<feature />
				<allauthors>
					<author>ശ്രീ  അതുലാനന്ദസ്വാമികൾ</author>
				</allauthors>
				<page>0023-0030</page>
			</entry>
			<entry>
				<title>സൗന്ദര്യലഹരിയുടെ അനുബന്ധം</title>
				<feature />
				<allauthors>
					<author>തപസ്യാനന്ദസ്വാമികൾ, വിവർത്തനം എസ്. വി. ഉണ്ണികൃഷ്ണൻ</author>
				</allauthors>
				<page>0031-0032</page>
			</entry>
			<entry>
				<title>സത്യാന്വേഷണം ശാസ്ത്രത്തിലും മതത്തിലും സ്വാമി വിവേകാനന്ദന്റെ വീക്ഷണം</title>
				<feature />
				<allauthors>
					<author>ഡോ. ജയ ലാൽമോഹൻ</author>
				</allauthors>
				<page>0033-0035</page>
			</entry>
			<entry>
				<title>ശ്രീമദ് ഭഗവദ്‌ഗീത</title>
				<feature />
				<allauthors>
					<author>പ്രശാന്താനന്ദസ്വാമി</author>
				</allauthors>
				<page>0036-0039</page>
			</entry>
			<entry>
				<title>വാർത്തകൾ</title>
				<feature />
				<allauthors />
				<page>0040-0040</page>
			</entry>
		</part>
		<part pnum="02" month="02" year="2014" info="">
			<entry>
				<title>അമൃതവാണി</title>
				<feature />
				<allauthors />
				<page></page>
			</entry>
			<entry>
				<title>ശ്രീരാമകൃഷ്ണവചനാമൃതം</title>
				<feature />
				<allauthors />
				<page></page>
			</entry>
			<entry>
				<title>കാരുണ്യഹൃദയം  (എഡിറ്റോറിയൽ)</title>
				<feature />
				<allauthors>
					<author>സദ്ഭവാനന്ദസ്വാമി</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>വിവേകചൂഡാമണി</title>
				<feature />
				<allauthors>
					<author>ശ്രീ രംഗനാഥാനന്ദസ്വാമികൾ</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>സ്വാമി തപസ്യാനന്ദ ( ജീവചരിത്രക്കുറിപ്പ് )</title>
				<feature />
				<allauthors>
					<author>സ്വാമി ത്യാഗാനന്ദ</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>യോഗവാസിഷ്ഠരാമായണം</title>
				<feature />
				<allauthors>
					<author>സ്വപ്രഭാനന്ദസ്വാമി</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>റാബിയാ അൽ അദാമിയാ</title>
				<feature />
				<allauthors>
					<author>വിവർത്തനം ലോകഹിതാനന്ദസ്വാമി</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>സ്വാമിജി പാശ്ചാത്യർക്ക് നൽകിയ സന്ദേശം</title>
				<feature />
				<allauthors>
					<author>ശ്രീ  അതുലാനന്ദസ്വാമികൾ</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>സൗന്ദര്യലഹരിയുടെ അനുബന്ധം</title>
				<feature />
				<allauthors>
					<author>തപസ്യാനന്ദസ്വാമികൾ, വിവർത്തനം എസ്. വി. ഉണ്ണികൃഷ്ണൻ</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>സത്യാന്വേഷണം ശാസ്ത്രത്തിലും മതത്തിലും സ്വാമി വിവേകാനന്ദന്റെ വീക്ഷണം</title>
				<feature />
				<allauthors>
					<author>ഡോ ജയ ലാൽമോഹൻ</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>ശ്രീമദ് ഭഗവദ്‌ഗീത</title>
				<feature />
				<allauthors>
					<author>പ്രശാന്താനന്ദസ്വാമി</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>വാർത്തകൾ</title>
				<feature />
				<allauthors />
				<page></page>
			</entry>
		</part>
		<part pnum="03" month="03" year="2014" info="">
			<entry>
				<title>അമൃതവാണി</title>
				<feature />
				<allauthors />
				<page></page>
			</entry>
			<entry>
				<title>ശ്രീരാമകൃഷ്ണവചനാമൃതം</title>
				<feature />
				<allauthors />
				<page></page>
			</entry>
			<entry>
				<title>യുഗാവതാരം  (എഡിറ്റോറിയൽ)</title>
				<feature />
				<allauthors>
					<author>സദ്ഭവാനന്ദസ്വാമി</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>വിവേകചൂഡാമണി</title>
				<feature />
				<allauthors>
					<author>ശ്രീ രംഗനാഥാനന്ദസ്വാമികൾ</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>യോഗവാസിഷ്ഠരാമായണം</title>
				<feature />
				<allauthors>
					<author>സ്വപ്രഭാനന്ദസ്വാമി</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>സ്വാമി തപസ്യാനന്ദ ( ജീവചരിത്രക്കുറിപ്പ് )</title>
				<feature />
				<allauthors>
					<author>സ്വാമി ത്യാഗാനന്ദ</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>കൃതജ്ഞതയുടെ മർമ്മരങ്ങൾ (കവിത)</title>
				<feature />
				<allauthors>
					<author>ബ്രഹ്മചാരി ശിവേശചൈതന്യ</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>ശ്രീമദ് ബ്രഹ്മാനന്ദസ്വാമികൾ</title>
				<feature />
				<allauthors>
					<author>അമൃത</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>ഭക്തി</title>
				<feature />
				<allauthors>
					<author>ഡോ. വി. രാമൻകുട്ടി</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>അവതാരവരിഷ്ഠൻ</title>
				<feature />
				<allauthors>
					<author>ഡോ. എം. ലക്ഷ്മീകുമാരി</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>വാർത്തകൾ</title>
				<feature />
				<allauthors />
				<page></page>
			</entry>
		</part>
		<part pnum="04" month="04" year="2014" info="">
			<entry>
				<title>അമൃതവാണി</title>
				<feature />
				<allauthors />
				<page></page>
			</entry>
			<entry>
				<title>ശ്രീരാമകൃഷ്ണവചനാമൃതം</title>
				<feature />
				<allauthors />
				<page></page>
			</entry>
			<entry>
				<title>ദേവീമാഹാത്മ്യം (എഡിറ്റോറിയൽ)</title>
				<feature />
				<allauthors>
					<author>സദ്ഭവാനന്ദസ്വാമി</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>വിവേകചൂഡാമണി</title>
				<feature />
				<allauthors>
					<author>ശ്രീ രംഗനാഥാനന്ദസ്വാമികൾ</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>യോഗവാസിഷ്ഠരാമായണം</title>
				<feature />
				<allauthors>
					<author>സ്വപ്രഭാനന്ദസ്വാമി</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>സ്വാമി തപസ്യാനന്ദ ( ജീവചരിത്രക്കുറിപ്പ് )</title>
				<feature />
				<allauthors>
					<author>സ്വാമി ത്യാഗാനന്ദ</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>സാറാ ഓളി ബുള്ളിനയച്ച കത്തുകൾ</title>
				<feature />
				<allauthors>
					<author>പ്രൊഫ. ബി. സുലോചനാ നായർ</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>തൗസൻറ് അയലന്റ്  പാർക്കിലെ ആനന്ദദിനങ്ങൾ</title>
				<feature />
				<allauthors>
					<author>അമൃത</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>ഗ്രന്ഥപരിചയം</title>
				<feature />
				<allauthors />
				<page></page>
			</entry>
			<entry>
				<title>ശ്രീമദ് ഭഗവദ്‌ഗീത</title>
				<feature />
				<allauthors>
					<author>പ്രശാന്താനന്ദസ്വാമി</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>വാർത്തകൾ</title>
				<feature />
				<allauthors />
				<page></page>
			</entry>
		</part>
		<part pnum="05" month="05" year="2014" info="">
			<entry>
				<title>അമൃതവാണി</title>
				<feature />
				<allauthors />
				<page></page>
			</entry>
			<entry>
				<title>ശ്രീരാമകൃഷ്ണവചനാമൃതം</title>
				<feature />
				<allauthors />
				<page></page>
			</entry>
			<entry>
				<title>സേവനഭാവം (എഡിറ്റോറിയൽ)</title>
				<feature />
				<allauthors>
					<author>സദ്ഭവാനന്ദസ്വാമി</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>വിവേകചൂഡാമണി</title>
				<feature />
				<allauthors>
					<author>ശ്രീ രംഗനാഥാനന്ദസ്വാമികൾ</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>യോഗവാസിഷ്ഠരാമായണം</title>
				<feature />
				<allauthors>
					<author>സ്വപ്രഭാനന്ദസ്വാമി</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>സ്വാമി തപസ്യാനന്ദ ( ജീവചരിത്രക്കുറിപ്പ് )</title>
				<feature />
				<allauthors>
					<author>ഇന്ദിരാ കൃഷ്ണകുമാർ</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>ഭക്തിസുധാരസം</title>
				<feature />
				<allauthors>
					<author>ഡോ. ഡി. മായ</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>കൽക്കട്ടയിൽ ഒരു സൂര്യോദയം</title>
				<feature />
				<allauthors>
					<author>വിജയൻ അവിണിശ്ശേരി</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>കൃത്സ്നാത്ഭുതസ്യ ഭഗവൻ, തവ സുപ്രഭാതം</title>
				<feature />
				<allauthors>
					<author>തുളസീതീർത്ഥൻ</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>ഭാരതസുര്യോദയം</title>
				<feature />
				<allauthors>
					<author>സുരേഷ് ബാബു കിള്ളിക്കുറിശ്ശിമംഗലം</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>ഭഗവദ്‌ഗീത</title>
				<feature />
				<allauthors>
					<author>പ്രശാന്താനന്ദസ്വാമി</author>
				</allauthors>
				<page></page>
			</entry>
			<entry>
				<title>വാർത്തകൾ</title>
				<feature />
				<allauthors />
				<page></page>
			</entry>
		</part>
		<part pnum="06" month="06" year="2014" info="">
			<entry>
				<title>അമൃതവാണി</title>
				<feature />
				<allauthors />
				<page></page>
